### ISSUE TITLE
Missing includes in Hotkeys.ahk and Hotstrings.ahk in HyperWindowSnap.ahk

### ISSUE THREAD

**Issue by userabuser** [glenviewjeff/HyperWindowSnap#2]
I noticed two includes in [`HyperWindowSnap.ahk`](https://github.com/glenviewjeff/HyperWindowSnap/blob/master/HyperWindowSnap.ahk#L1) that are not in this repo and which without, throw an error on execution:

```
#include %A_ScriptDir%\Hotkeys.ahk 
#include %A_ScriptDir%\Hotstrings.ahk
```

Are these required for any additional functionality?

Commenting these lines out allows the script to run.

Good work just the same... 

👍

**Comment by glenviewjeff** [comment]
Thanks so much, I hope you get good use out of it! Yes, those are my personal scripts that of course didn't belong in there. Just removed the lines, thanks for noticing!

**Comment by userabuser** [comment]
Great, I thought as much... Thanks again.
