### ISSUE TITLE
README.md: Typos

### ISSUE THREAD

**Issue by digitalAssetStore** [glenviewjeff/HyperWindowSnap#3]
Found typos in README.md
See https://github.com/glenviewjeff/HyperWindowSnap#shrink-windows

In the "Shrink Windows" table 
1) <kbd>Ctrl</kbd> + <kbd>Win</kbd> + <kbd>Numpad</kbd> and should be corrected with <kbd>**Alt**</kbd> + <kbd>Win</kbd> + <kbd>Numpad</kbd>
2) First line should be Markdown "<kbd>Alt</kbd> + <kbd>Win</kbd> + <kbd>Numpad</kbd>" with "Numpad", same like next table below.

Thanks for correction

**Comment by glenviewjeff** [comment]
Fixed, thanks for noticing this!
