### ISSUE TITLE
Detach Chrome Tab and Snap New Window => Code solution that works also with Microsoft Edge (Chromium) [2nd]

### ISSUE THREAD

**Issue by digitalAssetStore** [glenviewjeff/HyperWindowSnap#5]
The new Microsoft Edge (Chromium) uses the same engine Chromium, the following code change would add support for it.
Can this be added/changed please?

FROM: `#IfWinActive ahk_exe chrome.exe`
TO: `#If WinActive("ahk_exe chrome.exe") || WinActive("ahk_exe msedge.exe")`

Interesting that in this case for MS Edge (chromium) to work in function SplitSnapActiveWindow() also the first line must be changed
FROM: `Send ^l^c^w^n^v{enter}`
TO: 
```
Send ^l
Send ^c
Send ^w^n^v{enter}
```

Thanks in advance!

**Comment by digitalAssetStore** [comment]
PS: Updated with a second needed change in function SplitSnapActiveWindow() for MS Edge (chromium).

**Comment by glenviewjeff** [comment]
My assumption is that this is an Edge/PC performance issue and that the key sending rate is too fast. I can use SetKeyDelay to slow down the keypresses. I imagine closing the tab and opening a new window are the critical section.

**Comment by glenviewjeff** [comment]
I'll change the code as follows. I think I'd seen the script fail on Chrome as well, PC/memory/load depending.

```
SplitSnapActiveWindow(winPlaceVertical, winPlaceHorizontal, winSizeHeight) {
	Send ^l^c
  SetKeyDelay, 100
  Send ^w^n^v{enter}
  SetKeyDelay, -1
	sleep 500
	SnapActiveWindow(winPlaceVertical, winPlaceHorizontal, winSizeHeight)
}

```
