### ISSUE TITLE
Win+Numpad5: Maximize window

### ISSUE THREAD

**Issue by digitalAssetStore** [glenviewjeff/HyperWindowSnap#6]
Proposal to add 
<kbd>Win</kbd> + <kbd>Numpad 5</kbd> | Window will maximize to the screen.

The following code adds the functionality
```
#Numpad5::
    WinMaximize, A  ; Maximize the active window
```

PS: This is different to default <kbd>Win</kbd> + <kbd>Up</kbd>, because above always maximizes immediately and increases step by step until maximized.

**Comment by glenviewjeff** [comment]
I don't understand the distinction between Win+up and using the ahk WinMaximize. Doesn't Win+up always maximize immediately? And what do you mean by increases step by step?

**Comment by digitalAssetStore** [comment]
If you hold the window title with left mouse and drag it left-down is will end up using 1/4 of screen.
In this case Win+Up (first time) increases window to 1/2 (left-side)
Then Win+Up (second time) maximizes.

Win+Numpad5 = Maximizes immediately.

PS: When using before Win+Numpad1, then als Win+Up maximizes at once.
Seems to be any tiny difference there...

**Comment by glenviewjeff** [comment]
I think I'm going to hold off on that suggestion for now. You can obviously change it for your situation but the five-key may become useful for other features, namely the concept of dividing the windows into thirds, which is an open enhancement I'd filed. It will become confusing if the five-key means "maximize" in some contexts, but "move to the middle position" in others.
