### ISSUE TITLE
Maximized windows won't resize or move

### ISSUE THREAD

**Issue by geoxcaliber** [glenviewjeff/HyperWindowSnap#8]
First off; this is so awesome! I was just using powertoys fancyzones, and even that was good. And now there's this?? its so awesome! I love how snaping the windows is fixed to a certain number pad, so you won't have problems going back and forth through zones (not to mention it's super quick). Now, the problem. For me, when I have the window maximized, none of the keys work?? the window must first be made smaller, but it doesn't work when the window is in fullscreen. Can you take a look and see if it's the same with you too?

**Comment by glenviewjeff** [comment]
Glad you can make good use of it! The shrinking and growing feature is neat too but ironically I can never remember the hotkeys so I never end up using it, LOL. 

Anyhow, you're right, it doesn't work for maximized windows. I almost never maximize windows (besides literally F11 full screen mode) because I have a giant monitor, so it never comes up for me and/or when it did I didn't care. 

I'll look into it and see if I can detect full size windows and fix it.

**Comment by glenviewjeff** [comment]
This is the issue, should be easy to fix: https://www.autohotkey.com/boards/viewtopic.php?t=40604

**Comment by glenviewjeff** [comment]
Found the answer in this thread where someone was using AHK for a very similar application to HyperWindowSnap: https://www.autohotkey.com/boards/viewtopic.php?t=47001

```
	WinGet, MinMaxState, MinMax
	
	If (MinMaxState = 1) {
		WinRestore, A
	}
```

For some reason, not working for Chrome but appears to work for other windows.

**Comment by glenviewjeff** [comment]
Fixed it, try the latest version. Thanks for the report!

**Comment by geoxcaliber** [comment]
Great, thank you! Also, here's a trick that you may or not love combined with this xD. Control Panel > Ease of Access > Mouse > activate a window by hovering over it with the mouse. Now, just by hovering over a window, you can select it. Just hover over, and you're free to then use the shortcuts. By default, it's set to 500 ms which is incredibly slow. https://www.tenforums.com/tutorials/113268-change-time-activate-window-hovering-over-mouse-windows.html This shows you how to change it in Registry. I have mine set to 100 ms which is a lot better. I'm still testing out, might make it higher since sometimes pop-ups come up and I'm too slow to go to them so they disappear. Another trick you can do is this: #e::WinMinimize, A
#q::WinKill, A
#w:: WinMaximize, A
Return 
Easily kill, minimize, or maximize your windows that your CURRENTLY hovered over with a single button. Talk about power.
Anyway, thank you again for the script! Probably the best you could find in AHK.

**Comment by glenviewjeff** [comment]
Thanks for the tips, I'll check them out!
